# Generated by Django 5.0.5 on 2024-05-13 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_userresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
