# Generated by Django 5.0.5 on 2024-05-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_userresponse_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='test_session_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
