# Generated by Django 5.0.5 on 2024-05-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_testattempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresponse',
            old_name='time',
            new_name='date_attempted',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='attempt_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TestAttempt',
        ),
    ]
